CREATE TABLE IF NOT EXISTS `DB_hotel`.Staff(
S_ID INT AUTO_INCREMENT NOT NULL,
S_name VARCHAR(45),
S_position VARCHAR(45),
PRIMARY KEY(S_ID));

ALTER TABLE `DB_hotel`.Staff AUTO_INCREMENT = 100;


SELECT * FROM `DB_hotel`.Staff;